import './globals.css'
import { Merriweather } from 'next/font/google'

const merriweather = Merriweather({
  weight: ['400', '700'],
  subsets: ['latin-ext'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={merriweather.className}>{children}</body>
    </html>
  )
}
